package app

import (
	"fmt"
	"strconv"
	"strings"
	"time"
)

func (b *BotApp) CalculateTotalCost(baseCost int, draftConfig map[string]interface{}) int {
	multiplier := 1
	if val, ok := draftConfig["num_outputs"]; ok {
		switch v := val.(type) {
		case int:
			multiplier = v
		case float64:
			multiplier = int(v)
		case string:
			if i, err := strconv.Atoi(v); err == nil {
				multiplier = i
			}
		}
	}
	if multiplier < 1 { multiplier = 1 }
	return baseCost * multiplier
}

func (b *BotApp) ProcessImageGeneration(user *User, chatID int64, prompt string) {
	// REFRESH DATA USER: Pastikan kita punya data draft terbaru (termasuk foto yang baru diupload)
	freshUser, err := b.DB.GetOrCreateUser(user.ID)
	if err == nil {
		user = freshUser
	}

	modelConf := b.GetModelByID(user.SelectedModel)
	if modelConf.ID == "" { return }

	totalCost := b.CalculateTotalCost(modelConf.Cost, user.DraftConfig)
	fmt.Printf("[INFO] Gen Request | User: %d | Cost: %d | Prompt: %s\n", user.ID, totalCost, prompt)

	if err := b.DB.DeductCredit(user.ID, totalCost); err != nil {
		SendMessage(b.BotToken, chatID, fmt.Sprintf("❌ Insufficient Credits. Need: <b>%d</b>, You have: <b>%d</b>", totalCost, user.Credits), nil)
		return
	}

	doneChan := make(chan bool)
	go func() {
		for {
			select {
			case <-doneChan:
				return
			default:
				SendChatAction(b.BotToken, chatID, "upload_photo")
				time.Sleep(4 * time.Second)
			}
		}
	}()

	SendMessage(b.BotToken, chatID, fmt.Sprintf("🎨 <b>Generating...</b>\n(Cost: %d credits)", totalCost), nil)

	finalInput := user.DraftConfig
	imageURLs, err := b.Replicate.Generate(modelConf, prompt, finalInput) 
	
	doneChan <- true
	
	if err != nil {
		fmt.Printf("[ERROR] %v\n", err)
		go b.DB.AddCredit(user.ID, totalCost) 
		SendMessage(b.BotToken, chatID, b.I18n.Get(user.LanguageCode, "error_generic"), nil)
		return
	}

	displayPrompt := prompt
	if len(displayPrompt) > 200 {
		displayPrompt = displayPrompt[:197] + "..."
	}
	displayPrompt = strings.ReplaceAll(displayPrompt, "<", "&lt;")
	displayPrompt = strings.ReplaceAll(displayPrompt, ">", "&gt;")
	displayPrompt = strings.ReplaceAll(displayPrompt, "&", "&amp;")
	
	caption := fmt.Sprintf("✨ <b>Result for:</b>\n<code>%s</code>\n\nGenerated by <b>%s</b>", displayPrompt, modelConf.Name)

	if len(imageURLs) == 1 {
		SendPhoto(b.BotToken, chatID, imageURLs[0], caption)
	} else if len(imageURLs) > 1 {
		SendMediaGroup(b.BotToken, chatID, imageURLs, caption)
	} else {
		SendMessage(b.BotToken, chatID, "No image generated.", nil)
	}

	go b.DB.ClearState(user.ID)
}